index:
    path: /{_locale}
    controller: App\Controller\TechNews\IndexController::index
    defaults: { _locale: '%locale%' }
    requirements:
        _locale: en|fr

# Le RedirectController va effectuer une redirection sans avoir
# à passer par un contrôleur personnalisé...
accueil:
    path: /accueil
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: index
        permanent: true

# Permet d'éviter la création d'un controlleur personnalisé
# pour nos page static. Contact, Présention, Mentions Légales, ...
mentions_legales:
    path:         /mentions-legales
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: static/mentionslegales.html.twig